# Generated by Django 2.1.2 on 2019-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='maxstudent',
            field=models.IntegerField(default=100),
        ),
    ]
